networks:
  hackathon-network:
    driver: bridge
services:
  hackathon-agentic:
    build:
      context: "./services/agentic"
    container_name: "hackathon-agentic"
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    command: ["fastapi", "run", "./app/Agentic.py", "--port", "8001"]
    networks:
      - hackathon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 2s
      retries: 5
  hackathon-front:
    build:
      context: "./front"
      args:
        - VITE_BACKEND_URL=/api
    container_name: "hackathon-front"
    ports:
      - "8080:80"
    networks:
     - hackathon-network
